### ISSUE TITLE
BT1/2 Salinity rising, increase dosage of DI water from 2L to 4L per day

### ISSUE THREAD

**Issue by zdellaert** [Putnam-Lab/CBLS_Wetlab#15]

**Comment by zdellaert** [comment]
Increased frequency of dosage of 1000mL of DI water from twice a day (at 9:00 and 15:00) to four times a day  (at 9:00, 12:00, 15:00, and 18:00).

**Comment by hputnam** [comment]
@zdellaert can you please keep this issue open and add daily salinity data and water level info here until we figure out if this is enough to stabilize the system? Thank you!

**Comment by zdellaert** [comment]
Salinity log: 

- 10/30: 35.34
- 10/31: 35.48
- 11/01: 35.57
- 11/02: 35.66 Zoe changed DI dosing to be 4x a day, 1L per dose
- 11/03: 35.57, water level good
- 11/05, water level good
- 11/06: 35.51, water level good
- 11/07: 35.60, water level rising slightly with increased alk dosing
- 11/08: 35.77
- 11/09: 36.01, changed DI dosing to 4x a day, 1.25L per dose; turned off salt dosing.
- 11/09 in afternoon: 35.47
- 11/10: 35.75
- 11/13: 35.31; water level seems low due to evaporation so turned salt dosing back on to 1.5L 1X per day
- 11/14: 35.39
- 11/15: 35.19
- 11/16: 35.28

**Comment by hputnam** [comment]
@zdellaert it looks like the salinity is still increasing. The alk dosing is not much (max 120ml per day until stabilized). Please turn up the DI and turn down the salt mix dosing to try to deal with both the salinity and the water level.

**Comment by zdellaert** [comment]
Salinity this morning was 36.01. Seems like the DI dosing got changed back down to 2L per day when the alkalinity dosing was set up. Changed back to 4x a day, and increased amount to 1250mL a day to increase total dosing to 5L a day. Turned off salt mixing dosing temporarily while salt is being mixed and to try to lower the salinity of the tank.

**Comment by hputnam** [comment]
@zdellaert now that the dosing is back to "normal" can you please continue to report salinity and water level?

**Comment by zdellaert** [comment]
I have been adding it to the comment above so it's all in the same place!

**Comment by zdellaert** [comment]
BT1/2 salinity is stable around 35.3. We can increase dosage of DI if we want this to be lower, but it is no longer rising

**Comment by zdellaert** [comment]
Salinity has been dropping below 35, so I decreased the DI H2O dosing into BT1/2 from 1250mL 4x a day to 3x a day. Measurements 11/27-11/30:
34.88
34.72
34.67
34.81

**Comment by zdellaert** [comment]
Salinity has continued to drop below 35, so I decreased the DI H2O dosing into BT1/2 from 1250mL 3x a day to 2x a day. Measurements 12/04-12/08:
34.84
35.52
34.89
34.43
34.39
12/11: 34.25

**Comment by zdellaert** [comment]
Salinity is stable around 34.5 and slowly rising.
