### ISSUE TITLE
Increase and Stabilize alkalinity at ~2300 in blue tanks

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/CBLS_Wetlab#16]
@laurenzane please increase the Alk dosing to tank BT 3/4 with the existing Jebao dose line on 11/6.

@laurenzane please set up Alk dosing to tank BT 1/2 with the existing or new Jebao dose pump by 11/8.

Alk Dosing Information
https://fritzaquatics.com/products/fritz-rpm-calcium-buffer-system-pt-1-alkalinity

_"Begin by measuring the alkalinity of the aquarium water and determine how much you wish to increase it. Each mL of Pt 1 will increase the alkalinity in 1 US gallon (3.78 L) of water by 2.1 dKH (0.75 meq/mL). One teaspoon (5 mL) will raise 10 US gallons by 1.06 dKH (0.38 meq/L). Do not exceed 5 mL per 10 gallons daily, and always avoid an immediate +/* 0.2 change in pH."_

**Comment by laurenzane** [comment]
We need to know the number of gallons that are in BT1/2 and BT3/4 before changing the pump programming. 

Conversion factor for total alkalinity: 1μmol/kg = .00205meq/liter. We measure TA in umol/kg. We need to increase BT1/2 from ~1000μmol/kg to 2300 μmol/kg and BT3/4 from ~1400 μmol/kg to 2300 μmol/kg. 

1300 μmol/kg =  2.665 meq/liter = 7.462 dkh
900 μmol/kg = 1.845 meq/liter = 5.166 dkh 

Begin by measuring the alkalinity of the aquarium water and determine how much you wish to increase it. Each mL of Pt 1 will increase the alkalinity in 1 US gallon (3.78 L) of water by 2.1 dKH (0.75 meq/mL). One teaspoon (5 mL) will raise 10 US gallons by 1.06 dKH (0.38 meq/L). Do not exceed 5 mL per 10 gallons daily, and always avoid an immediate +/* 0.2 change in pH.

**Comment by hputnam** [comment]
@laurenzane The volume in gallons can be calculated by the geometry of the tank dimensions that have water in them (BT 3/4 volume = BT 3/4 + Header) (BT 1/2 volume = BT 1/2).

**Comment by laurenzane** [comment]
BT1/2 and BT3/4 approx dims: 27.5 in x 10 in x 99.5 in = 118.45 gal 
HT approx dims: 55 x 30 x 18 in = 29700 in ^3 = 126.57 gal
HT is about half full = ~ 64 gal 

BT1/2 has a total of 118.45 gal 
BT3/4/HT has about 182.45 gal 

1 mL/gal of Part 1 solution raises the alkalinity by 2.1dkH

We need to increase to 2.46 mL per gal for 236.9 mL for BT1/2 and to 3.55 ml/gal mL for BT3/4/HT.

BT3/4 are already being dosed at 5 mL a day. 

To avoid having dramatic changes in pH, I will increase slowly

Dosing will start tomorrow at 9am when I am there to record changes in pH. 

Schedule: BT1/2: 25mL @ 3:00, 9:00, 15:00, 21:00
BT3/4: 300mL @ 3:00, 9:00, 15:00, 21:00

**Comment by laurenzane** [comment]
15 minutes after 9:00am addition, pH was measured at -60.2 mV in BT1/2 and -39.5 mV in BT3/4. I scheduled the second dosage for 12pm, so I could be there to monitor it as well. 

Yesterday's measurements for BT1/2 were: -54.4
BT3/4: -40.7

**Comment by hputnam** [comment]
@laurenzane please calculate and report pH on the total scale, as the mV don't mean anything without temp and the tris calibration curve.

**Comment by hputnam** [comment]
@laurenzane please measure and report the pH on the total scale immediately before the addition of Alk, during, and after on 11/8.

**Comment by hputnam** [comment]
@laurenzane please measure and report the pH on the total scale immediately before the addition of Alk, during, and after on 11/9.

**Comment by hputnam** [comment]
@laurenzane please measure and report the pH on the total scale immediately before the addition of Alk, during, and after on 11/14.

**Comment by hputnam** [comment]
@laurenzane please measure and report the pH on the total scale immediately before the addition of Alk, during, and after on 11/15.
