### ISSUE TITLE
Apex pH probe does not reflect total pH

### ISSUE THREAD

**Issue by laurenzane** [Putnam-Lab/CBLS_Wetlab#19]
I calibrated the apex pH probe in BT1 with a two-point 7.00 and 10.01 solution with reference standards. 

Immediately afterward, I recorded discrete measurements for all tanks. The apex probe in BT1 reads 7.55 for pH, but the total pH, when calculated is 7.850598.

What is the pH range that we are aiming for? I can increase the dosage to 40 mL per day in BT1 and 2 and increase the dosage to 60 mL per day in BT3 and 4.

**Comment by daniellembecker** [comment]
@laurenzane after replacing the pH probes for BT 1/2 and BT 3/4 I think they are now reading correctly to the discrete measurements, so hopefully this was the issue!
