### ISSUE TITLE
Header Salt/DI water DOS not responding to configuration and pumping water incessantly

### ISSUE THREAD

**Issue by laurenzane** [Putnam-Lab/CBLS_Wetlab#4]
The DOS labeled "Header_DI"/"Header_Salt" has been making a clicking sound, blinking blue, and pumping water incessantly. Additionally, the DOS log entries have not recorded any additions of water to the system though the pumps were actively running. Zoe Dellaert took the DOS offline on 20220116 due to the header tank flooding.  

Yesterday (20230117) I took steps to reset and reconfigure the Apex DOS as well as clean the salt build up cables and pump heads. When I left, the DOS had a constant orange light on indicating that it was working correctly. However, sometime during the night, the DOS started pumping off schedule (incessantly, blinking blue) and I took it offline again today (20230118). 

I submitted a support request with Neptune (#996085). From the [Neptune Systems forum](https://forum.neptunesystems.com/showthread.php?16327-dos-pump-one-will-not-stop) it appears there may be water damage to the circuit board and I anticipate we need to send the DOS in to be replaced. 

https://user-images.githubusercontent.com/64224939/213240059-3c8d3ae4-8b0b-4d88-ac0b-64a4c8b85f07.mov

**Comment by hputnam** [comment]
Let's track it to the repair completion here as well. Thanks!
