### ISSUE TITLE
Orion Salinity Probe Drifting

### ISSUE THREAD

**Issue by laurenzane** [Putnam-Lab/CBLS_Wetlab#5]
The probe (SN: n/a) for the Orion meter (SN: G 14012) gives an initial reading that does not hold consistently. The value measured drifts to a lower number indefinitely.

Using the [Orion_Star-A215-A325 manual](https://github.com/Putnam-Lab/CBLS_Wetlab/files/10538478/Orion_Star-A215-A325.pdf)I performed a self test which passed.

Afterwards, I performed the stability test using the conductivity probe and the 50.00ms/cm reference solution. The conductivity probe did NOT pass the stability test. NOTE: in the future the stability test is only for the pH probe according to technical support.

After failing the stability test, the manual recommends that users contact technical support 1-800-225-1480. I spoke with a representative and he did not recommend replacing the probe unless it was reading values that were highly inaccurate. He recommended switching continuous reading to autoread, which I was able to do. 

The concern with switching a continuous reading to autoread to ignore the drift is that we cannot verify that the initial reading is the closest to the value of the saltwater. The outcome of switching to autoread is that we will not be able to validate daily measurements or the salinity of the salt mixing tank. If we continue to have readings with a large margin of error, potentially introducing salt water that deviates from our lab conditions could cause a physiological response from the corals to compensate for salt water that is either more or less salty than 34.5psu.

**Comment by hputnam** [comment]
@laurenzane Can you please clarify why this has an impact and what the outcome is for repeated measurements in a standard?

**Comment by laurenzane** [comment]
@hputnam updated!

**Comment by hputnam** [comment]
@laurenzane can you report the variability in measurements of the same standard solution measured 5 times per day for 3 days per week?

**Comment by laurenzane** [comment]
Issue resolved. Probe was held in salinity standard (1413 us/cm) measured 5x a day for 3 days and reflected 1413us/cm standard measurement without wavering.

**Comment by hputnam** [comment]
@laurenzane can you add data or plot with mean ± sem measured in the standard? Thanks!
