### ISSUE TITLE
update wetlab parameter code to output graphics with readable X axes and a single graph panel that is updated by push daily

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/CBLS_Wetlab#8]

**Comment by hputnam** [comment]
@JillAshey please post the html for the plot output here for TA and for the other multi-panel plots. @laurenzane please set up a 2x per week autopost (slackbot) of the ph/sal/temp plot and a monthly post of the TA plot on slack cbls wetlab channel

**Comment by hputnam** [comment]
@JillAshey Can you please confirm here when you have included the new pH tris calibrations for each probe?

@laurenzane the link to the multi-panel figure should not change. Please finish setting up the slackbot on Thursday 11/2 so that it will automatically post the plots every Tuesday and Thursday

**Comment by hputnam** [comment]
@laurenzane the link to the multi-panel figure should not change. Please finish setting up the slackbot so that it will automatically post the plots every Tuesday and Thursday @laurenzane please post the slackbot and confirm and close this issue on 11/6/23.

**Comment by hputnam** [comment]
@laurenzane Please finish setting up the slackbot so that it will automatically post the plots every Tuesday and Thursday @laurenzane please post the slackbot and confirm and close this issue on 11/14/23.

**Comment by JillAshey** [comment]
Slack bot has been set up so that it will automatically post link to daily measurement plots every Tuesday and Thursday at 12pm EST.

**Comment by hputnam** [comment]
@JillAshey  Please remove mV plot and added dashed horizontal lines representing the upper and lower ranges that are acceptable for each parameter.

**Comment by JillAshey** [comment]
pH mV plot removed and dashed lines have been added corresponding to upper and lower thresholds for each parameter. Upper and lower thresholds can be changed in the daily measurement script
